Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <inlineHelpText>Description</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre</description>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies1</relationshipName>
    <type>Lookup</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Script__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/Test/ManagersTest.cls
@isTest
public class ManagersTest {
	
   private static String jsonString {get;set;}
   private static ScriptManager sman;
   private static List<JsonMovieData.Movie> movieData {get;set;}

   @isTest
   public static void ScriptCreationTest()
   {
      StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
      mock.setStaticResource('FilmsLessHuge');
      mock.setStatusCode(200);
      mock.setHeader('Content-Type', 'application/json');
      Test.setMock(HttpCalloutMock.class, mock);
       
      HTTPResponse res = MockStaticResource.getInfoFromExternalService(
            'https://example.com/example/test');
      //System.debug(res.getBody());
      movieData = JsonMovieDataHandler.parsingJson(res.getBody().toString());
      sman = new ScriptManager();  //.processScripts(movies);
      sman.processScripts(movieData);
      Script__c script = [SELECT Id, Title__c, Description__c FROM Script__c LIMIT 1];
      System.assertNotEquals(null, script, 'A Script record should have been created.');
      System.assertEquals(movieData[0].script.name, script.Title__c, 'The title should match.');
   }
    
   @isTest
   public static void MovieCreationTest()
   {
       StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
       mock.setStaticResource('FilmsLessHuge');
       mock.setStatusCode(200);
       mock.setHeader('Content-Type', 'application/json');
       Test.setMock(HttpCalloutMock.class, mock);
       
       HTTPResponse res = MockStaticResource.getInfoFromExternalService(
            'https://example.com/example/test');
       //System.debug(res.getBody());
       movieData = JsonMovieDataHandler.parsingJson(res.getBody().toString());
       sman = new ScriptManager();  //.processScripts(movies);
       sman.processScripts(movieData);
       MovieManager mman = new MovieManager(sman); 
       System.debug(movieData);
       List<Movie__c> createdMovies = mman.createMovies(movieData);
       Movie__c firstMovie = createdMovies[0];
       System.assertEquals('Avatar', firstMovie.Title__c, 'First movie title should be "Avatar".');
       System.assertEquals('Action;Adventure;Fantasy', firstMovie.Genre__c, 'First movie genre should be "Action;Adventure;Fantasy;Science_Fiction".');
       System.assertEquals('19995',firstMovie.TMDBID__c,'TMDB ID supposed to be 19995');
       
   }
}