Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre</description>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/GenreValidation.cls
public class GenreValidation 
{
    private Set<String> validGenres = new Set<String>();
    
   	public void loadValidGenres() {
        Schema.DescribeFieldResult fieldResult = Movie__c.Genre__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry entry : picklistEntries) {
            validGenres.add(entry.getValue());
        }
    }
    
    public Set<String> returnValidGenres()
    {
        return validGenres;
    }
    
    public String validateGenres(String genreStr) {
        if (String.isBlank(genreStr)) return null;

        List<String> genres = genreStr.split(';');
        List<String> validGenresList = new List<String>();
		
        for(String gen : validGenres)
        {
            System.debug(gen);
        }
        
        for (String genre : genres) {
           
            if (validGenres.contains(genre.trim())) {
                validGenresList.add(genre.trim());
            } else {
                System.debug('Invalid genre value: ' + genre.trim());
            }
        }
        return validGenresList.isEmpty() ? null : String.join(validGenresList, ';');
    }

}