Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/MovieTMDBSyncBatch.cls
public class MovieTMDBSyncBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful 
{
    public Database.QueryLocator start(Database.BatchableContext BC) {
        
        return Database.getQueryLocator([
            SELECT Id, tmdbId__c, TMDBSyncDate_c__c
            FROM Movie__c 
            WHERE (TMDBSyncDate_c__c = NULL OR TMDBSyncDate_c__c < LAST_N_DAYS:30) 
            AND tmdbId__c != NULL
        ]);
    }
    
    public void execute(Database.BatchableContext BC, List<Movie__c> scope) {
        for (Movie__c movie : scope) {
           
            tmdbMovieDetails tmdbData = tmdb.getMovieDetails(movie.tmdbId__c);
            
            if (tmdbData != null) {
                
                movie.Revenue__c = tmdbData.revenue;
                movie.Rating__c = tmdbData.vote_average;
                movie.TMDBSyncDate_c__c = Date.today(); 
            }
        }
        
        update scope;
    }
    
    public void finish(Database.BatchableContext BC) {
      
    }
}