Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>Budget</description>
    <inlineHelpText>Budget</inlineHelpText>
    <label>Budget</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <inlineHelpText>Description</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre</description>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/Test/MovieTriggerTest.cls
@isTest
public class MovieTriggerTest {

    @isTest
    static void testInsert() {
        Test.setMock(HttpCalloutMock.class, new MockMovieDetails());

        
        DisableUpdateTrigger__c bypassSetting = DisableUpdateTrigger__c.getOrgDefaults();
        bypassSetting.UpdateTrigger__c = true;
        upsert bypassSetting;

        Test.startTest();

      
        Movie__c mov = new Movie__c();
        mov.TMDBID__c = '550'; 

        insert mov;
		Test.stopTest();
    
        Movie__c movieToTest = [SELECT TMDBID__c, Title__c, Description__c, Revenue__c, Budget__c, Poster_URL__c, Rating__c, Release_Date__c, Genre__c FROM Movie__c WHERE Id = :mov.Id];
		
        
        System.assertNotEquals(null, movieToTest, 'Movie record should have been inserted.');
        System.assertEquals('Fight Club', movieToTest.Title__c, 'Title field should match the inserted value.');
        System.assertEquals('550', movieToTest.TMDBID__c, 'TMDBID__c field should match the inserted value.');
        System.assertEquals(100853753, movieToTest.Revenue__c, 'Revenue should match the mock response.');
        System.assertEquals(63000000, movieToTest.Budget__c, 'Budget should match the mock response.');
        System.assertEquals(8.433, movieToTest.Rating__c, 'Rating should match the mock response.');
        System.assertEquals(Date.valueOf('1999-10-15'), movieToTest.Release_Date__c, 'Release date should match the mock response.');
        System.assertEquals('Comedy;Drama;Thriller', movieToTest.Genre__c, 'Genre should match the mock response.');

        
    }    

    @isTest
    static void testFailedInsert() {
        Test.setMock(HttpCalloutMock.class, new MockMovieDetails());

      
        DisableUpdateTrigger__c bypassSetting = DisableUpdateTrigger__c.getOrgDefaults();
        bypassSetting.UpdateTrigger__c = true;
        upsert bypassSetting;

        Test.startTest();

    
        Movie__c mov = new Movie__c();
        mov.TMDBID__c = '';
        try {
            insert mov; 
  
            System.assert(false, 'Expected an exception to be thrown due to invalid TMDBID__c.');
        } catch (DmlException e) {
     
            System.assert(e.getMessage().contains('TMDBID__c cannot be empty'), 'Expected error message about empty TMDBID__c');
        }

      
        List<Movie__c> movies = [SELECT TMDBID__c, Title__c FROM Movie__c WHERE TMDBID__c = ''];
        System.assertEquals(0, movies.size(), 'No movie records should be inserted with empty TMDBID__c.');

        Test.stopTest();
    }
}