Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>Budget</description>
    <inlineHelpText>Budget</inlineHelpText>
    <label>Budget</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <inlineHelpText>Description</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre</description>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/Test/MovieMapperTest.cls
@isTest
public class MovieMapperTest {

    @isTest
    static void testMapMovieNegative_NullMovieDetails() {
    
        MovieMapper movieMapper = new MovieMapper();
        Movie__c newmov = new Movie__c(); 
        
        Id idmov = newmov.id;  

   
        Movie__c result = movieMapper.mapMovie(idmov, null);

 
        System.assertNotEquals(null, result);
        System.assertEquals(null, result.TMDBID__c);
        System.assertEquals(null, result.Title__c);
        System.assertEquals(null, result.Description__c);
        System.assertEquals(null, result.Revenue__c);
        System.assertEquals(null, result.Budget__c);
        System.assertEquals(null, result.Poster_URL__c);
        System.assertEquals(null, result.Rating__c);
        System.assertEquals(null, result.Release_Date__c);
        System.assertEquals(null, result.Genre__c);
    }


    @isTest
    static void testMadeGenreStringNegative_EmptyList() {
        MovieMapper movieMapper = new MovieMapper();
        
      
        String result = movieMapper.madeGenreString(new List<tmdbMovieDetails>());

      
        System.assertEquals(null, result);
    }

    @isTest
    static void testMadeGenreStringNegative_NullList() {
       
        MovieMapper movieMapper = new MovieMapper();

    
        String result = movieMapper.madeGenreString(null);

   
        System.assertEquals(null, result);
    }
}