Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/Test/MovieTMDBSyncBatchTest.cls
@isTest
public class MovieTMDBSyncBatchTest {
   
    
    @isTest
    static void testBatchExecution() {
                
        Test.setMock(HttpCalloutMock.class, new MockMovieDetails());
        DisableUpdateTrigger__c bypassSetting = DisableUpdateTrigger__c.getOrgDefaults();
        bypassSetting.UpdateTrigger__c = true;
        upsert bypassSetting;
      
        Test.startTest();
        List<Movie__c> movies = new List<Movie__c>{new Movie__c(Title__c = 'Movie 1', TMDBID__c = '101'),
            new Movie__c(Title__c = 'Movie 2', TMDBID__c = '102', TMDBSyncDate_c__c = Date.today().addDays(-60))
         };
        insert movies;

        MovieTMDBSyncBatch batch = new MovieTMDBSyncBatch();
        Database.executeBatch(batch);
        Test.stopTest();
		
        List<Id> ids = new List<Id>();

		for(Movie__c mov : movies)
        {
            ids.add(mov.Id);
        }

        List<Movie__c> updatedMovies = [SELECT Id,  Title__c,Revenue__c, Rating__c, TMDBSyncDate_c__c FROM Movie__c WHERE Id IN :ids];
        for (Movie__c movie : updatedMovies) {
            System.debug(movie.Title__c);
    
            System.assertNotEquals(null, movie.Revenue__c, 'Revenue should be updated');
            System.assertNotEquals(null, movie.Rating__c, 'Rating should be updated');
            System.assertEquals(Date.today(), movie.TMDBSyncDate_c__c, 'Sync date should be updated to today');
        }
    }
}