Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>Budget</description>
    <inlineHelpText>Budget</inlineHelpText>
    <label>Budget</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre</description>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies1</relationshipName>
    <type>Lookup</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Script__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/MovieManager.cls
public class MovieManager 
{
    private ScriptManager scriptManager;
    private Map<String, Movie__c> existingMoviesMap = new Map<String, Movie__c>();
    private Set<String> tmdbIds = new Set<String>();
    private GenreValidation validation = new GenreValidation();

    public MovieManager(ScriptManager scriptManager) {
        this.scriptManager = scriptManager;
        //System.debug('validation of genres');
        validation.loadValidGenres();
    }

    public List<Movie__c> createMovies(List<JsonMovieData.Movie> movieData) {
        extractTmdbIds(movieData);
        loadExistingMovies();
        List<Movie__c> movieContainer = new List<Movie__c>();
        
        for(JsonMovieData.Movie jsmovie : movieData) {
            if (!existingMoviesMap.containsKey(jsmovie.tmdb_id)) {
                Movie__c movie = mapJsonMovieToMovie(jsmovie);
                movieContainer.add(movie);
            }
        }
        return movieContainer;
    }

    private void extractTmdbIds(List<JsonMovieData.Movie> movieData) {
        for(JsonMovieData.Movie jsmovie : movieData) {
            tmdbIds.add(jsmovie.tmdb_id);
        }
    }

    private void loadExistingMovies() {
        for (Movie__c existingMovie : [SELECT Id, TMDBID__c FROM Movie__c WHERE TMDBID__c IN :tmdbIds]) {
            existingMoviesMap.put(existingMovie.TMDBID__c, existingMovie);
        }
    }

    private Movie__c mapJsonMovieToMovie(JsonMovieData.Movie jsmovie) {
        Movie__c movie = new Movie__c();
        movie.LegacyId__c = jsmovie.id;
        movie.Title__c = jsmovie.name;
        movie.TMDBID__c = jsmovie.tmdb_id;
        movie.Rating__c = jsmovie.rating; 
        movie.Budget__c = jsmovie.budget;
        movie.Revenue__c = jsmovie.revenue;
        movie.TMDBSyncDate_c__c = Date.today();
        movie.Release_Date__c = parseReleaseDate(jsmovie.release_date);
        movie.Genre__c = validation.validateGenres(jsmovie.genre);
        
        Script__c script = scriptManager.getScriptByLegacyId(jsmovie.script.id);
        if (script != null) {
            movie.Script__c = script.Id;
        }
        
        return movie;
    }

    private Date parseReleaseDate(String releaseDateStr) {
        List<String> dateParts = releaseDateStr.split('/');
        if (dateParts.size() == 3) {
            Integer month = Integer.valueOf(dateParts[0]);
            Integer day = Integer.valueOf(dateParts[1]);
            Integer year = Integer.valueOf(dateParts[2]);
            return Date.newInstance(year, month, day);
        }
        return null;
    }


}