Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>Budget</description>
    <inlineHelpText>Budget</inlineHelpText>
    <label>Budget</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <inlineHelpText>Description</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre</description>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/MovieMapper.cls
public class MovieMapper {
    
    private GenreValidation validation = new GenreValidation();
    
    private String getBaseImageUrl()
    {
        String baseUrl;
        String posterSize;

        tmdbImageDetails imageDetails = tmdb.getImageDetails();

        try
        {
            baseUrl = imageDetails.images.base_url;
            posterSize = 'original';  
            return baseUrl+posterSize;          
        }
        catch(Exception ex)
        {
            System.debug(ex.getMessage());
            System.debug('Was unable to obtain tmdb base image hosting url.');
        }
        return '';
    }
    
    public Movie__c mapMovie(Id movieId, tmdbMovieDetails movieDetails) {


        if(movieDetails == null) 
        {
            throw new NoMovieDetailsException('movieDetails strucutre was null.');
        }

        Movie__c movie = new Movie__c();

        try
        {
         validation.loadValidGenres();   
        }
        catch(Exception ex)
        {
            System.debug(ex.getMessage());
        }
        

        movie.Id = movieId;
        movie.TMDBID__c = String.valueOf(movieDetails.id);
        movie.Title__c = movieDetails.original_title;
        movie.Description__c = movieDetails.overview;
        movie.Revenue__c = movieDetails.revenue;
        movie.Budget__c = movieDetails.budget;
        movie.Poster_URL__c = getBaseImageUrl()+movieDetails.poster_path;
        movie.Rating__c = movieDetails.vote_average;
        movie.Release_Date__c = Date.valueOf(movieDetails.release_date);
        try
        {
            movie.Genre__c = validation.validateGenres(madeGenreString(new List<tmdbMovieDetails>{movieDetails}));
        }        
        catch(Exception ex){
            System.debug(ex.getMessage());
            System.debug('Genre insertion failed.');
        }
        return movie;
    }
    
    public String madeGenreString(List<tmdbMovieDetails> tmdbMovies) 
    {
        List<String> genreNamesList = new List<String>();
        
        if (tmdbMovies != null && !tmdbMovies.isEmpty()) {
            for (tmdbMovieDetails movie : tmdbMovies) {
                if (movie.genres != null && !movie.genres.isEmpty()) {
                    for (tmdbMovieDetails.Genre genre : movie.genres) {
                        genreNamesList.add(genre.name.trim());
                    }
                }
            }
        }
    
        return genreNamesList.isEmpty() ? null : String.join(genreNamesList, ';');
    }
}