Student5-idpbootcamp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Student5-idpbootcamp/force-app/main/default/objects/Movie__c/fields/TMDBID__c.field-meta.xml
<CustomField>
    <fullName>TMDBID__c</fullName>
    <label>TMDBID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Student5-idpbootcamp/force-app/main/default/classes/NecessaryMovies.cls
public class NecessaryMovies
{
    public static List<Movie__c> getMoviesToUpdate(List<Movie__c> newMovies, Map<Id, Movie__c> oldMoviesMap, Boolean isInsert, Boolean isUpdate) 
    {
        List<Movie__c> moviesNeedingUpdate = new List<Movie__c>();

        for (Movie__c movie : newMovies) {
            Movie__c oldMovie = oldMoviesMap?.get(movie.Id);
            if (isInsert || (isUpdate && movie.TMDBID__c != oldMovie.TMDBID__c))
            {
                moviesNeedingUpdate.add(movie);
            }
        }
        
        return moviesNeedingUpdate;
    }
}